### ISSUE TITLE
`this.PIXI = this.PIXI || {};` can't run in ES6 & `strict mode`

### ISSUE THREAD

**Issue by finscn** [pixijs/particle-emitter#100]
the struct of pixi-particles dist file is like this : 
```
this.PIXI = this.PIXI || {};
(function (exports, pixi) {
	'use strict';

// ... ...

}(this.PIXI.particles = this.PIXI.particles || {}, PIXI));

```

In es6 & es5 with `strict mode` ,
the `this` is undefined .

So I think you should refactor the build scripts of pixi-particles.

**Comment by finscn** [comment]
![image](https://user-images.githubusercontent.com/288367/55686936-d7fc1100-5999-11e9-8e8a-17cd0259e219.png)

this are some information about this .

but I know nothing about rollup , So I don't know how to modify it .

**Comment by andrewstart** [comment]
package.json already has an entry for `[module](https://github.com/rollup/rollup/wiki/pkg.module)`, so Rollup should automatically pull in an ES6 version of the library. You'll need to look into why you are pulling in the `dist/pixi-particles.js` version instead. The first thing you should check is to make sure that you are importing the `pixi-particles` library from node_modules, rather than `dist/pixi-particles.js` directly.

**Comment by finscn** [comment]
I forked `pixi-particles` , and I want to use my forked pixi-particles in ES5 with "use strict" .
And whatever , the  `this.PIXI` is a bad code.

**Comment by finscn** [comment]
When I use   "use strict" , and  mix my js file and pixi.js  into one file (named  all-in-one.js),

the  `this.PIXI` can't run , the error is  `this is undefined` .

**Comment by andrewstart** [comment]
You need to change your Rollup configuration to pull in the [module](https://github.com/rollup/rollup/wiki/pkg.module) export instead of `dist/pixi-particles.js`. This may involve just removing existing configuration that specifies that path, if you have it present.
