### ISSUE TITLE
Destroyed property

### ISSUE THREAD

**Issue by Metatron92** [pixijs/particle-emitter#116]
Hello.

Could you add property "destroyed" with boolean data true / false for emitter?

Thank you.

**Comment by andrewstart** [comment]
This would be simple enough. While looking to see if there are properties that I could use to run a getter without having to add a full boolean, I realized that `destroy()` doesn't clear out anything that couldn't be fixed with another `init()` call and setting `parent`, which are all acceptable use cases. Would it be more convenient to have a `ready` boolean that checks those things (`false` before `init()` and after `destroy()`, `true` if able to run)?

**Comment by Metatron92** [comment]
Property "ready" match me too, if after destroy it change to false

**Comment by andrewstart** [comment]
Finally got around to this in version 5.0.1.
