### ISSUE TITLE
Is the project will keep update?

### ISSUE THREAD

**Issue by asd4486** [pixijs/particle-emitter#206]
Hello, the project hasn't been updated for a while, I want to know if it is still alive. Or I need to upgrade by myself :/
Thank you

**Comment by andrewstart** [comment]
The project is still maintained, but it tends to not need many updates. It works with the latest release of Pixi, and once V8 is released it will probably need only minimal changes to be updated (although module changes will probably break support for older releases).

**Comment by asd4486** [comment]
So if I didn't misunderstood, if I want more feature I need to add by myself?
Also we made a particle editor for EmitterConfigV3 (not 100% done yet), don't know if you are interested or not

**Comment by andrewstart** [comment]
Yeah, I tend to not have time to work on requests, so with the easy extendability of the library I am happy to look at PRs for generally useful features others develop. I am definitely interested in particle editors, since I built in the editor information to the latest version of the library but again, didn't have time to develop anything from there.
